apiVersion: v1
kind: Service
metadata:
  name: simple-web-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
  labels:
    app: simple-web
spec:
  type: LoadBalancer
  selector:
    app: simple-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
